repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.4.8"
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: mixed-line-ending
  
  #- repo: https://github.com/pycqa/bandit
  #  rev: 1.7.4
  #  hooks:
  #  - id: bandit
  #    exclude: tests/

  # !COMMENTED OUT FOR NOW:
  # TAIPY latest version 3.1.1 (2024/06/12) is affected with 3 CVEs
  #  jinja2 3.1.4 is affected with 1 CVE
  #  flask-cors 4.0.0 is affected with 1 CVE
  #  pymongo 4.6.1 is affected with 1 CVE

  # - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  #   rev: v1.3.1
  #   hooks:
  #     - id: python-safety-dependencies-check
